[table]
name = "before_new_password"

[columns.before_new_password_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "before_new_password_"

[columns.payload]
type = "Json"

[columns.expired_at]
type = "DateTime"

[columns.completed_at]
type = "DateTime"
