[table]
name = "credential"

[columns.credential_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "credential_"

[columns.name]
type = "String"
min_length = 1
max_length = 64

[knowns.email]
primary_key = "0x018d938bdf7e73029d9fee4b47762169"
identity = "0x018d938bdf7e7d27a440bc2ae08ed412"

[knowns.onetime_password]
primary_key = "0xd2d8c8f225e14666a9007d241cc22c1b"
identity = "0xa6ae875660b64b418356eb856bb5cca2"
