[table]
name = "user_permission"

[columns.user_pk]
type = "PrimaryKey"

[columns.permission_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "user_permission_"

[columns.created_at]
type = "DateTime"
