[table]
name = "user_credential"

[columns.user_credential_pk]
type = "PrimaryKey"

[columns.user_pk]
type = "PrimaryKey"

[columns.credential_pk]
type = "PrimaryKey"

[columns.external_id]
type = "String"
min_length = 1
