[table]
name = "user_group__has__role"

[columns.user_group_pk]
type = "PrimaryKey"

[columns.role_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "user_group__has__role_"

[columns.created_at]
type = "DateTime"
