[table]
name = "user_group__has__permission"

[columns.user_group_pk]
type = "PrimaryKey"

[columns.permission_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "user_group__has__permission_"

[columns.created_at]
type = "DateTime"
