[table]
name = "user_activity"

[columns.user_pk]
type = "PrimaryKey"

[columns.activity_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "user_activity_"

[columns.ip_address]
type = "IpAddr"
