[table]
name = "user_group__has__user"

[columns.user_group_pk]
type = "PrimaryKey"

[columns.user_pk]
type = "PrimaryKey"

[columns.id]
type = "Identity"
prefix = "user_group__has__user_"

[columns.created_at]
type = "DateTime"
