[table]
name = "user_credential__has__hasher"

[columns.user_credential__has__hasher_pk]
type = "PrimaryKey"

[columns.user_credential_pk]
type = "PrimaryKey"

[columns.hasher_pk]
type = "PrimaryKey"

[columns.hash]
type = "Hash"

[columns.expired_at]
type = "DateTime"
