[package]
name = "guard"
version = "0.1.0"
edition = "2021"

[dependencies]
auth_database = { path = "../auth_database" }
chrono = "0.4.34"
new_type = { path = "../new_type" }
rocket = "0.5.0"
tokio = "1.36.0"
