[package]
name = "auth_event"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-sns = "1.16.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
